---
- name: RackHD Demonstration Server
  hosts: local
  vars:
    rackhd_version: ""
    deb_repository: "deb https://dl.bintray.com/rackhd/debian trusty release"
  sudo: no
  roles:
    - rackhd-builds
