---
- name: RackHD Demonstration Server
  hosts: local
  vars:
    rackhd_version: ""
    deb_repository: "deb https://dl.bintray.com/rackhd/debian trusty release"
  sudo: no
  roles:
    - apt
    - build
    - git
    - rabbitmq
    - mongodb
    - node
    - isc-dhcp-server
    - monorail
    - config_admin_ip
    - snmptool
    - ipmitool
    - integrationtest
    - postgresql
    - setuptools
    - rackhd-builds
