# apt_repository apparently requires this to run in Ansible 1.5
- apt: pkg=python-pip state=present
  sudo: yes

- pip: name=setuptools extra_args='--upgrade'
  sudo: yes

- pip: name=virtualenv extra_args='--upgrade'
  sudo: yes
